version: "3"

services:
  api:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/api
    networks:
        - mynet

networks:
  mynet:
    external: true
#
#networks:
#  mynet:
#    driver: bridge
